### PR TITLE
Migrate to fastapi

### PR DESCRIPTION
**Pull request by janniss91**
The branch contains the migration from Flask to FastAPI.

I have tried to keep everything as it was and only changed the Framework.
The most drastic change is probably the introduction of request and response models for type checking.

There are 2 new to-do comments in the code.
If you take a look at them and tell me how to proceed, they can already be resolved in this merge request.

### CODE REVIEW

**Comment by janniss91** [comment]
Nice to read that this is going in the right direction!

I have changed the model names and corrected their data types on the basis of the Java classes in the backend.

About the first improvement you suggest:
I understand you don't want to restrict the usage to uvicorn as a server. 
However, I think the import outside the "if name == main" does not affect this.
It should neither prevent the use of a different server nor affect the performance of the script or any of its functions.
As far as I know (according to PEP8, https://www.python.org/dev/peps/pep-0008/#imports), imports should always be kept on top of the file.
If there's something specific I don't know about server usage that you're referring to here, I'll change this of course.
I'm not really familiar with deployment processes so it's possible that I'm missing something important.

**Comment by ramonziai** [comment]
Thanks!

I understand the importance of adhering to guidelines and certainly import statements in the middle of the code somewhere don't do much for readability. I just want to avoid forcing dependencies that aren't really necessary. I therefore suggest the following: let's get rid of both the import and the main method altogether, since the standard way of running an ASGI app for development is actually something like "uvicorn main:app --reload" with no uvicorn dependencies in the file. We just need to add that to the README so it's clear how to run the server for development.

For production, the preferred way is to wrap this component in a Docker container (hence the Dockerfile), which supplies the server environment needed. To adjust this to FastAPI, all that is needed here is to change the base Docker image in the first line to "tiangolo/uvicorn-gunicorn". If you have Docker installed, you can test the Docker build with "docker build -t ramonziai/isaac-ml-service ./" from the project directory.

Could you tackle these two things?

**Comment by janniss91** [comment]
Yes sure, I will take care of these two things!
In the afternoon, I will start working on it.

Thank you for explaining the procedure of using Docker.

**Comment by janniss91** [comment]
I've removed the main method so for development the service can now only be run from the commandline.  
I assumed that you wanted uvicorn completely removed from the project dependencies, right?
Therefore, I changed the Readme in a way that explains to a potential new developer how to install and use uvicorn in case they want to use it as a server for development.

I also changed the Dockerfile the way you explained to me.
I managed to create the container, however, I couldn't check how to use/start the service inside of it because I didn't find out how yet.
It would be good if you could double-check that I haven't made any mistakes there.

**Comment by ramonziai** [comment]
Changes are looking good! You should be able to run the Docker image using something like 'docker run --name isaac-ml-service -p 8000:8000 ramonziai/isaac-ml-service'.
Before I merge this, I would like to confirm it's working. If I remember correctly, the obstacle to testing was constructing a well-formed request using an example XMI. To get this working, you can read in an XMI file, b64encode its raw bytes (basically ignoring the file's encoding) and send with something like this:
`in_file = open("xmifile", "rb")`
`bytes = in_file.read()`
`in_file.close()`
`encoded_bytes = base64.b64encode(bytes)`
`instance_dict = {}`
`instance_dict['modelId'] = "default"`
`instance_dict['cas'] = encoded_bytes`
`# this needs the 'requests' module`
`requests.post('http://localhost:8000/predict', json=instance_dict)`

**Comment by janniss91** [comment]
I just wanted to let you know that I'm on it but it'll still take me a bit to get familiar with Docker as it seems.
As soon as I have a result, I'll tell you.

**Comment by janniss91** [comment]
Hi Ramon, I've checked that the code works in the docker environment and it does.

Instead of writing a new demo file (which would have been necessary due to the migration to fastAPI) I decided to start writing tests right away, which we can use later.

In the tests some issues came up:
1. It seems like the migration to fastAPI makes sending byte strings even harder because it makes use of the json library directly for model conversion. JSON does not even accept the base64 strings (or at least I haven't found a way yet.)
2. In the "/train" request the function pandas.read_table is depracated and will have to be changed to pandas.read_csv.
3. I think it would be good to throw error codes when something in the request functions does not work. Up to now, a message is returned but the service still sends a 200 request .
I have examplarily changed this in "/trainFromCases" request function by using an HTTPException as suggested in the fastAPI documentation and tested the behavior.

Would you like me to push my tests and the small changes I made in main.py?
I haven't pushed it yet because I thought you might first want to finish this pull request.

**Comment by ramonziai** [comment]
Thanks for the update! Tests are a really good idea, feel free to push them. Concerning your points:

1. A base64-encoded string is just a string and shouldn't impact FastAPI at all. Perhaps there is a misunderstanding here that we could clarify once you've pushed the corresponding test so I can see what's going on.
2. Ok, we can change that method call, but since it has nothing to do with this PR, let's disregard that for now.
3. Good point, this should be changed. I think it would be best to let FastAPI handle all unexpected errors itself, and only return our own messages when something expected (e.g. 'no model here') happens. Since this is part of the FastAPI migration, let's get that working in this branch still.

Once issues 1. and 3. are taken care of, I can merge the pull request.

**Comment by janniss91** [comment]
I've pushed the tests and worked on 3., which involved adding appropriate error messages.

For the byte string (1.) I haven't found a solution.
It's probably better if you take a look as you said.

I tested it and I get a bytestring when encoding the string with base64.

Screenshot from 2020-07-21 11-22-29

I don't know what's happening to the string once it's been sent through the API so I don't know if just converting it to a normal "UTF-8" string as shown in the picture could help us.

**Comment by ramonziai** [comment]
I've looked at the test and two things occurred to me that may contribute to the problem but don't have anything to do with byte strings or base64:

1. in main.predict(), the model ID is retrieved as 'model_id_' but then later referred to as 'model_id' (no '_'), which will not work unless I'm missing something fundamental.
2. in test_main(), instance_dict specifies model ID as 'modelId' but in main.ClassificationInstance it's called 'model_id' - this will not be correctly deserialized.

Could you fix these issues? Otherwise, I very much like the pytest setup with the fixtures etc!

**Comment by ramonziai** [comment]
Thanks, I think I found the culprit: it seems one needs to explicitly decode the base64 bytestring to ASCII (which base64 is by definition), which results in a string that can be sent via JSON. Deserialization, feature extraction and prediction now seem to work fine, but test_predict now returns a validation error for CASPrediction, which still needs to be resolved.

**Comment by janniss91** [comment]
I've seen your change, thanks for the help there!

On this basis I could make all tests except for the last one (which belongs to a future pull request) run.
I guess this should be finished now.

I still have one suggestion for the main.py function.
Maybe it would be a good idea to refactor the model loading process into a class (```ModelLoader``` or something similar)?
This would make it much easier to handle the variables combined with the model loading process, I think.
In the tests I had to import the main file directly to manipulate the variables to check the test behavior, which seems to me a bit unintuitive and error prone.

However, if you wanted this change, this would probably be something for a different pull request I suppose?

**Pull request merged**
